### ISSUE TITLE
How to use causal_nf on a custom dataset?

### ISSUE THREAD

**Issue by hyxie2023** [psanch21/causal-flows#2]
Hello! Your work has inspired me a lot. I would like to inquire about how to apply causal_nf to a custom dataset, such as a dataframe, not just limited to the few predefined ones in scm_dataset. Thank you!

**Comment by psanch21** [comment]
Hi @hyxie2023,

Thanks for your interest in our work! In that case, I suggest you have a look at the German Dataset. The data is stored as a numpy array so it represents a case that is similar to yours :) 

You should implement:

- Your custom dataset, see [GermanDataset](https://github.com/psanch21/causal-flows/blob/main/causal_nf/datasets/german_credit.py) for reference.
- Your custom preparator, see [GermanPreparator](https://github.com/psanch21/causal-flows/blob/main/causal_nf/preparators/german_preparator.py) for reference. 
- Your custom SEM, see [GermanCredit](https://github.com/psanch21/causal-flows/blob/main/causal_nf/sem_equations/german_credit.py) for reference.

Hope this helps!

**Comment by hyxie2023** [comment]
Thank you for your response, the methods you mentioned are very helpful to me!
